# Generated by Django 5.1 on 2024-08-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_no', models.IntegerField(default=0)),
                ('arabic_name', models.CharField(blank=True, max_length=500)),
                ('arabic_description', models.TextField(blank=True)),
                ('english_name', models.CharField(blank=True, max_length=500)),
                ('english_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
